server:
  port: 8080
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8082/eureka/
      
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: http://customer-service:8084/
          predicates:
            - Path=/customer/**
        - id: product-service
          uri: http://product-service:8085/
          predicates:
            - Path=/product/**
